#!/usr/bin/env python3

import sys
import subprocess

COMMANDS = ['catalog', 'query', 'verify', 'move', 'remove', 'stats', 'duplicates', 'export', 'getMetadata', 'cloudUpload', 'cloudDownload']
if __name__=='__main__':
    if len(sys.argv) == 1 or sys.argv[1] in ('-h', '--help'):
        print('\n    mcat: media cataloging tool')
        print(f'\n    Usage: {sys.argv[0]} COMMAND [command args]')
        print('\n    Commands:')
        for command in COMMANDS:
            print(f'        {command}')
        sys.exit(0)

    command = sys.argv[1]
    args = sys.argv[2:]

    if command not in COMMANDS:
        print(f'command must be one of {COMMANDS}')
        sys.exit(1)

    subprocess.run([f'mcat-{command}.py'] + args)
        